In [29]:
!git clone https://github.com/marafasal/Credit-card-fraud-detection-model-LRM-.git

Cloning into 'Credit-card-fraud-detection-model-LRM-'...
warning: You appear to have cloned an empty repository.

In [30]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
#loading the dataset
fraud_data=pd.read_csv('/content/creditcard.csv')

In [3]:
print(fraud_data.head())

   Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010

        V26       V27       V28  Amount  Class
0 -0.189115  0.133558 -0.021053  149.62    0.0
1  0.125895 -0.008983  0.014724    2.69    0.0
2 -0.139097 -0.055353 -0.059752  378.66    0.0
3 -0.221929  0.062723  0.061458  123.50    0.0
4  0.502292  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [4]:
fraud_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53571 entries, 0 to 53570
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    53571 non-null  int64
 1   V1      53571 non-null  float64
 2   V2      53571 non-null  float64
 3   V3      53571 non-null  float64
 4   V4      53571 non-null  float64
 5   V5      53571 non-null  float64
 6   V6      53571 non-null  float64
 7   V7      53571 non-null  float64
 8   V8      53571 non-null  float64
 9   V9      53571 non-null  float64
 10  V10     53571 non-null  float64
 11  V11     53571 non-null  float64
 12  V12     53571 non-null  float64
 13  V13     53571 non-null  float64
 14  V14     53571 non-null  float64
 15  V15     53571 non-null  float64
 16  V16     53571 non-null  float64
 17  V17     53571 non-null  float64
 18  V18     53571 non-null  float64
 19  V19     53571 non-null  float64
 20  V20     53571 non-null  float64
 21  V21     53571 non-null  float64
 22  V22     53571 non-null  float64
 23  V23     53570 non-null  float64
 24  V24     53570 non-null  float64
 25  V25     53570 non-null  float64
 26  V26     53570 non-null  float64
 27  V27     53570 non-null  float64
 28  V28     53570 non-null  float64
 29  Amount  53570 non-null  float64
 30  Class   53570 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 12.7 MB

In [5]:
fraud_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [6]:
#chcking the distribution of legit transaction and fraudulent transaction
fraud_data['Class'].value_counts()

Class
0.0    53417
1.0      153
Name: count, dtype: int64

Highly imbalanced data
0---Normal transaction
1---Fraudulent transaction

In [7]:
legit=fraud_data[fraud_data.Class==0]
fraud=fraud_data[fraud_data.Class==1]
print(legit.shape)
print(fraud.shape)

(53417, 31)
(153, 31)

In [8]:
#statistical measurement of the data
legit.Amount.describe
fraud.Amount.describe

<bound method NDFrame.describe of 541        0.00
623      529.00
4920     239.93
6108      59.00
6329       1.00
          ...
50211      1.00
50537      1.00
52466      1.00
52521    105.99
52584      1.00
Name: Amount, Length: 153, dtype: float64>

In [9]:
fraud_data.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,30011.81811,-0.222505,-0.014659,0.722511,0.163565,-0.242775,0.109604,-0.097131,0.042665,0.104805,...,0.046251,-0.031568,-0.106396,-0.038408,0.008094,0.134794,0.019825,0.002289,0.003902,94.251260
1.0,27472.24183,-7.468948,5.326389,-10.100308,5.793812,-5.528864,-2.230554,-7.865700,3.617647,-3.492917,...,0.455720,0.891045,-0.218399,-0.277419,-0.084305,0.240593,0.136258,0.586389,0.028185,97.616013

Building an undersample datset of normal transaction and fraudulent transaction
Taking equivalence of fraudulent transaction randomly

In [10]:
legit_sample=legit.sample(153)

In [11]:
#concatenating the data
new_dataset=pd.concat([legit_sample,fraud],axis=0)

In [12]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
11707,20004,-0.609280,0.324170,2.332258,0.685363,-0.251954,0.201330,-0.261476,0.255465,0.824664,...,0.099974,0.401092,0.164470,0.184384,-0.796844,0.423440,0.100979,0.143811,48.12,0.0
19861,30605,-2.942689,-0.305654,2.372448,2.958839,1.030385,0.756611,0.774724,-0.062448,-0.982876,...,-0.518293,-0.683736,0.388874,-0.046548,0.247019,-0.400000,-0.776042,0.458178,97.49,0.0
18911,29861,-3.603452,3.485655,-5.666760,1.795182,-1.901784,-1.804616,-1.003523,2.698631,-0.259349,...,-0.132448,-0.592919,0.237287,-0.466545,0.020737,-0.339446,0.113291,-0.238101,89.99,0.0
31673,36464,0.284232,-2.672275,-2.197135,-1.197980,1.073917,3.386306,-0.028904,0.540700,-0.968630,...,0.472831,-0.138582,-0.746295,1.088256,0.722183,-0.116029,-0.123727,0.105063,630.06,0.0
50454,44498,-1.065885,0.016914,1.851130,0.535272,-0.209000,2.033633,-0.280307,0.597893,0.758823,...,-0.027608,0.602597,-0.404047,-1.206566,0.634133,0.995818,0.438779,0.104832,124.00,0.0

In [13]:
new_dataset['Class'].value_counts()

Class
0.0    153
1.0    153
Name: count, dtype: int64

In [14]:
new_dataset.groupby("Class").mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,28604.647059,-0.375957,0.190840,0.563245,0.147841,-0.343905,0.266180,0.066158,0.019624,0.087501,...,-0.024845,-0.037802,-0.066729,-0.149895,-0.027203,0.082394,0.011143,0.044415,-0.010667,122.284641
1.0,27472.241830,-7.468948,5.326389,-10.100308,5.793812,-5.528864,-2.230554,-7.865700,3.617647,-3.492917,...,0.455720,0.891045,-0.218399,-0.277419,-0.084305,0.240593,0.136258,0.586389,0.028185,97.616013

In [16]:
#split data into features and target
X=new_dataset.drop(columns="Class",axis=1)
Y=new_dataset['Class']

In [17]:
print(X)

        Time        V1        V2        V3        V4        V5        V6  \
11707  20004 -0.609280  0.324170  2.332258  0.685363 -0.251954  0.201330
19861  30605 -2.942689 -0.305654  2.372448  2.958839  1.030385  0.756611
18911  29861 -3.603452  3.485655 -5.666760  1.795182 -1.901784 -1.804616
31673  36464  0.284232 -2.672275 -2.197135 -1.197980  1.073917  3.386306
50454  44498 -1.065885  0.016914  1.851130  0.535272 -0.209000  2.033633
...      ...       ...       ...       ...       ...       ...       ...
50211  44393 -4.617461  3.663395 -5.297446  3.880960 -3.263551 -0.918547
50537  44532 -0.234922  0.355413  1.972183 -1.255593 -0.681387 -0.665732
52466  45463 -1.476893  2.122314 -1.229470  1.201849 -0.343264 -1.317704
52521  45501  1.001992  0.047938 -0.349002  1.493958  0.186939  0.190966
52584  45541 -1.519244  2.308492 -1.503599  2.064101 -1.000845 -1.016897

             V7        V8        V9  ...       V20       V21       V22  \
11707 -0.261476  0.255465  0.824664  ...  0.189302  0.099974  0.401092
19861  0.774724 -0.062448 -0.982876  ... -1.000721 -0.518293 -0.683736
18911 -1.003523  2.698631 -0.259349  ...  0.004501 -0.132448 -0.592919
31673 -0.028904  0.540700 -0.968630  ...  1.433429  0.472831 -0.138582
50454 -0.280307  0.597893  0.758823  ...  0.477668 -0.027608  0.602597
...         ...       ...       ...  ...       ...       ...       ...
50211 -5.715262  0.831040 -2.457034  ... -0.346456  2.698175 -0.027081
50537  0.059110 -0.003153  1.122451  ... -0.003469  0.220670  0.912107
52466 -1.528142 -0.620953 -1.213040  ...  0.276893  1.186036 -0.040215
52521 -0.001112  0.147140  0.580415  ...  0.016004 -0.334417 -1.014315
52584 -2.059731 -0.275166 -1.562206  ...  0.175019  1.307871  0.102826

            V23       V24       V25       V26       V27       V28  Amount
11707  0.164470  0.184384 -0.796844  0.423440  0.100979  0.143811   48.12
19861  0.388874 -0.046548  0.247019 -0.400000 -0.776042  0.458178   97.49
18911  0.237287 -0.466545  0.020737 -0.339446  0.113291 -0.238101   89.99
31673 -0.746295  1.088256  0.722183 -0.116029 -0.123727  0.105063  630.06
50454 -0.404047 -1.206566  0.634133  0.995818  0.438779  0.104832  124.00
...         ...       ...       ...       ...       ...       ...     ...
50211  0.366775 -0.123011 -0.300457 -0.239996 -0.183463 -0.073360    1.00
50537 -0.286338  0.451208  0.188315 -0.531846  0.123185  0.039581    1.00
52466 -0.238930  0.110144  0.045418 -0.569232  0.481019 -0.047555    1.00
52521 -0.128427 -0.946242  0.456090 -0.453206  0.046627  0.064698  105.99
52584 -0.017746  0.149696 -0.096602 -0.369115 -0.019244 -0.208319    1.00

[306 rows x 30 columns]

In [18]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [19]:
print(X.shape,X_train.shape,X_test.shape)

(306, 30) (244, 30) (62, 30)

Model training

In [20]:
model=LogisticRegression()

In [21]:
#training the LRM with the training dataset
model.fit(X_train,Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

Accuracy score

In [22]:
#accuracy of training data
X_training_data=model.predict(X_train)
training_data_accuracy=accuracy_score(X_training_data,Y_train)

In [27]:
print("The training data accuracy is: ",training_data_accuracy)

The training data accuracy is:  0.9754098360655737

In [24]:
#accuracy of testing data
X_testing_data=model.predict(X_test)
testing_data_accuracy=accuracy_score(X_testing_data,Y_test)

In [28]:
print(f'The testing data accuracy is : {testing_data_accuracy}')

The testing data accuracy is : 0.9516129032258065